INSERT IGNORE INTO roles (id, name) VALUES (1, 'ROLE_USER');
INSERT IGNORE INTO roles (id, name) VALUES (2, 'ROLE_ADMIN');
INSERT IGNORE INTO institutions (name, description) VALUES ('"Dbam o Zdrowie"', 'Pomoc dzieciom z ubogich rodzin.');
INSERT IGNORE INTO institutions (name, description) VALUES ('"A kogo"', 'Pomoc w wybudzaniu dzieci ze śpiączki.');
INSERT IGNORE INTO institutions (name, description) VALUES ('"Dla dzieci"', 'Pomoc osobom znajdującym się w trudnej sytuacji życiowej.');
INSERT IGNORE INTO institutions (name, description) VALUES ('"Bez domu"', 'Pomoc dla osób nie posiadających miejsca zamieszkania.');
INSERT IGNORE INTO categories (name) VALUES ('ubrania, które nadają się do ponownego użycia');
INSERT IGNORE INTO categories (name) VALUES ('ubrania do wyrzucenia');
INSERT IGNORE INTO categories (name) VALUES ('zabawki');
INSERT IGNORE INTO categories (name) VALUES ('książki');
INSERT IGNORE INTO categories (name) VALUES ('inne');